#!/usr/bin/bash

if ! command -v "lua-language-server" > /dev/null 2>&1; then
  CURDIR="$(pwd)"
  cd "$HOME/.local" || return
  git clone https://github.com/LuaLS/lua-language-server
  cd lua-language-server || return
  if ./make.sh; then
    echo "LuaLS was installed successfully"
  fi
  cd "$CURDIR" || return
fi

if ! command -v "typescript-language-server" > /dev/null 2>&1; then
  curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh
  sudo -E bash nodesource_setup.sh
  sudo apt-get install -y nodejs
  npm install --global typescript typescript-language-server
  #shellcheck disable=SC2181
  if (($? == 0)); then
    echo "TypeScript LS was installed successfully"
  fi
fi

if ! command -v "clangd-19" > /dev/null 2>&1; then
  sudo apt install clangd-19
  #shellcheck disable=SC2181
  if (($? == 0)); then
    echo "Clangd installes successfully"
  fi
fi

if ! command -v "pyright-langserver" > /dev/null 2>&1; then
  LOCAL_PYTHON_VENV=".local/python-venv/virt_env"
  sudo apt install python3.11 pydoc3.11-venv
  mkdir -p "$LOCAL_PYTHON_VENV"
  python3.11 -m venv "$LOCAL_PYTHON_VENV"
  if [[ ! "$PYTHON_VENV" ]]; then
    #shellcheck disable=SC2016
    echo 'export $PYTHON_VENV="$HOME/.local/python-venv/virt_env"'
  fi
  installation=$?
  "$LOCAL_PYTHON_VENV/bin/pip3" install pyright
  if ! alias vpip > /dev/null 2>&1; then
    #shellcheck disable=SC2016
    echo 'alias vpip="$PYTHON_VENV/bin/pip3"' > "$HOME/.zshrc"
  fi
  vpipalias=$?
  if [[ $vpipalias -eq 0 ]]; then
    echo "alias \"vpip\" added successfully"
  fi
  if ! alias vpython > /dev/null 2>&1; then
    #shellcheck disable=SC2016
    echo 'alias vpython="$PYTHON_VENV/bin/python3"' > "$HOME/.zshrc"
  fi
  vpythonalias=$?
  if [[ $vpythonalias -eq 0 ]]; then
    echo "alias \"vpython\" added successfully"
  fi
  if [[ $installation -eq 0 ]]; then
    echo "Pyright installed successfully"
  fi
fi
