require("config.colorscheme")
require("config.lualine")
require("config.completions")
require("config.lspconfig")
require("config.treesitter")
require("config.icons")
require("config.nvim-tree")
require("config.keymaps")

require("ibl").setup()
