require("config.colorscheme")
require("config.completions")
require("config.lualine")
require("config.lspconfig")
require("config.treesitter")
require("config.icons")
require("config.neo-tree")
require("config.keymaps")

require("nvim-autopairs").setup({})
